steps:
# Step 1: Build the Docker container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/prefab-atlas-468301-k0/sales-apps/sales-trainer', '.']

# Step 2: Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/prefab-atlas-468301-k0/sales-apps/sales-trainer']

# Step 3: Run the training container
# This executes the ENTRYPOINT in your Dockerfile (train.py)
# The trained 'model.pkl' will be created in the workspace.
- name: 'us-central1-docker.pkg.dev/prefab-atlas-468301-k0/sales-apps/sales-trainer'
  id: 'RunTraining'

# Step 4: Copy the trained model to a Cloud Storage bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model.pkl', 'gs://prefab-atlas-468301-k0/sales-apps/model.pkl']

options:
  logging: CLOUD_LOGGING_ONLY